In [145]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
# Get html data from url
r = requests.get('https://www.spaceweatherlive.com/en/solar-activity/top-50-solar-flares')

In [146]:
root = BeautifulSoup(r.content,'html5lib')

In [147]:
# Get table data
table = root.find('table')

In [148]:
# Create new Table
new_table = pd.DataFrame(columns=['rank', 'x_class', 'date', 'region', 'start_time', 'max_time', 'end_time', 'movie'], index = range(0,50))

# Put data in table
row_marker = 0
for row in table.find_all('tr'):
    column_marker = 0
    columns = row.find_all('td')
    row_marker += 1
    for column in columns:
        if (row_marker > 1):
            new_table.iat[row_marker-2,column_marker] = column.get_text()
            column_marker += 1

In [149]:
new_table

,rank,x_class,date,region,start_time,max_time,end_time,movie
0,1,X28.0,2003/11/04,0486,19:29,19:53,20:06,MovieView archive
1,2,X20.0,2001/04/02,9393,21:32,21:51,22:03,MovieView archive
2,3,X17.2,2003/10/28,0486,09:51,11:10,11:24,MovieView archive
3,4,X17.0,2005/09/07,0808,17:17,17:40,18:03,MovieView archive
4,5,X14.4,2001/04/15,9415,13:19,13:50,13:55,MovieView archive
5,6,X10.0,2003/10/29,0486,20:37,20:49,21:01,MovieView archive
6,7,X9.4,1997/11/06,8100,11:49,11:55,12:01,MovieView archive
7,8,X9.3,2017/09/06,2673,11:53,12:02,12:10,View archive
8,9,X9.0,2006/12/05,0930,10:18,10:35,10:45,MovieView archive
9,10,X8.3,2003/11/02,0486,17:03,17:25,17:39,MovieView archive
10,11,X8.2,2017/09/10,2673,15:35,16:06,16:31,View archive
11,12,X7.1,2005/01/20,0720,06:36,07:01,07:26,MovieView archive
12,13,X6.9,2011/08/09,1263,07:48,08:05,08:08,MovieView archive
13,14,X6.5,2006/12/06,0930,18:29,18:47,19:00,MovieView archive
14,15,X6.2,2005/09/09,0808,19:13,20:04,20:36,MovieView archive
15,16,X6.2,2001/12/13,9733,14:20,14:30,14:35,MovieView archive
16,17,X5.7,2000/07/14,9077,10:03,10:24,10:43,MovieView archive
17,18,X5.6,2001/04/06,9415,19:10,19:21,19:31,MovieView archive
18,19,X5.4,2012/03/07,1429,00:02,00:24,00:40,MovieView archive
19,20,X5.4,2003/10/23,0486,08:19,08:35,08:49,MovieView archive
20,21,X5.4,2005/09/08,0808,20:52,21:06,21:17,MovieView archive
21,22,X5.3,2001/08/25,9591,16:23,16:45,17:04,MovieView archive
22,23,X4.9,1998/08/18,8307,22:10,22:19,22:28,View archive
23,24,X4.9,2014/02/25,1990,00:39,00:49,01:03,MovieView archive
24,25,X4.8,2002/07/23,0039,00:18,00:35,00:47,MovieView archive
25,26,X4.0,2000/11/26,9236,16:34,16:48,16:56,MovieView archive
26,27,X3.9,1998/08/19,8307,21:35,21:45,21:50,View archive
27,28,X3.9,2003/11/03,0488,09:43,09:55,10:19,MovieView archive
28,29,X3.8,2005/01/17,0720,06:59,09:52,10:07,MovieView archive
29,30,X3.7,1998/11/22,8384,06:30,06:42,06:49,MovieView archive
30,31,X3.6,2003/05/28,0365,00:17,00:27,00:39,MovieView archive
31,32,X3.6,2004/07/16,0649,13:49,13:55,14:01,MovieView archive
32,33,X3.6,2005/09/09,0808,09:42,09:59,10:08,MovieView archive
33,34,X3.4,2006/12/13,0930,02:14,02:40,02:57,MovieView archive
34,35,X3.4,2001/12/28,9767,20:02,20:45,21:32,MovieView archive
35,36,X3.3,1998/11/28,8395,04:54,05:52,06:13,MovieView archive
36,37,X3.3,2002/07/20,0039,21:04,21:30,21:54,MovieView archive
37,38,X3.3,2013/11/05,1890,22:07,22:12,22:15,MovieView archive
38,39,X3.2,2013/05/14,1748,00:00,01:11,01:20,MovieView archive
39,40,X3.1,2014/10/24,2192,21:07,21:41,22:13,MovieView archive
40,41,X3.1,2002/08/24,0069,00:49,01:12,01:31,MovieView archive
41,42,X3.0,2002/07/15,0030,19:59,20:08,20:14,MovieView archive
42,43,X2.8,1998/08/18,8307,08:14,08:24,08:32,View archive
43,44,X2.8,2001/12/11,9733,07:58,08:08,08:14,MovieView archive
44,45,X2.8,2013/05/13,1748,15:48,16:05,16:16,MovieView archive
45,46,X2.7,2015/05/05,2339,22:05,22:11,22:15,MovieView archive
46,47,X2.7,1998/05/06,8210,07:58,08:09,08:20,MovieView archive
47,48,X2.7,2003/11/03,0488,01:09,01:30,01:45,MovieView archive
48,49,X2.6,2005/01/15,0720,22:25,23:02,23:31,MovieView archive
49,50,X2.6,1997/11/27,8113,12:59,13:17,13:20,MovieView archive

In [150]:
# Drop the last column
new_table = new_table.drop('movie', 1)

In [151]:
new_table

   rank x_class        date region start_time max_time end_time
0     1   X28.0  2003/11/04   0486      19:29    19:53    20:06
1     2   X20.0  2001/04/02   9393      21:32    21:51    22:03
2     3   X17.2  2003/10/28   0486      09:51    11:10    11:24
3     4   X17.0  2005/09/07   0808      17:17    17:40    18:03
4     5   X14.4  2001/04/15   9415      13:19    13:50    13:55
5     6   X10.0  2003/10/29   0486      20:37    20:49    21:01
6     7    X9.4  1997/11/06   8100      11:49    11:55    12:01
7     8    X9.3  2017/09/06   2673      11:53    12:02    12:10
8     9    X9.0  2006/12/05   0930      10:18    10:35    10:45
9    10    X8.3  2003/11/02   0486      17:03    17:25    17:39
10   11    X8.2  2017/09/10   2673      15:35    16:06    16:31
11   12    X7.1  2005/01/20   0720      06:36    07:01    07:26
12   13    X6.9  2011/08/09   1263      07:48    08:05    08:08
13   14    X6.5  2006/12/06   0930      18:29    18:47    19:00
14   15    X6.2  2005/09/09   0808      19:13    20:04    20:36
15   16    X6.2  2001/12/13   9733      14:20    14:30    14:35
16   17    X5.7  2000/07/14   9077      10:03    10:24    10:43
17   18    X5.6  2001/04/06   9415      19:10    19:21    19:31
18   19    X5.4  2012/03/07   1429      00:02    00:24    00:40
19   20    X5.4  2003/10/23   0486      08:19    08:35    08:49
20   21    X5.4  2005/09/08   0808      20:52    21:06    21:17
21   22    X5.3  2001/08/25   9591      16:23    16:45    17:04
22   23    X4.9  1998/08/18   8307      22:10    22:19    22:28
23   24    X4.9  2014/02/25   1990      00:39    00:49    01:03
24   25    X4.8  2002/07/23   0039      00:18    00:35    00:47
25   26    X4.0  2000/11/26   9236      16:34    16:48    16:56
26   27    X3.9  1998/08/19   8307      21:35    21:45    21:50
27   28    X3.9  2003/11/03   0488      09:43    09:55    10:19
28   29    X3.8  2005/01/17   0720      06:59    09:52    10:07
29   30    X3.7  1998/11/22   8384      06:30    06:42    06:49
30   31    X3.6  2003/05/28   0365      00:17    00:27    00:39
31   32    X3.6  2004/07/16   0649      13:49    13:55    14:01
32   33    X3.6  2005/09/09   0808      09:42    09:59    10:08
33   34    X3.4  2006/12/13   0930      02:14    02:40    02:57
34   35    X3.4  2001/12/28   9767      20:02    20:45    21:32
35   36    X3.3  1998/11/28   8395      04:54    05:52    06:13
36   37    X3.3  2002/07/20   0039      21:04    21:30    21:54
37   38    X3.3  2013/11/05   1890      22:07    22:12    22:15
38   39    X3.2  2013/05/14   1748      00:00    01:11    01:20
39   40    X3.1  2014/10/24   2192      21:07    21:41    22:13
40   41    X3.1  2002/08/24   0069      00:49    01:12    01:31
41   42    X3.0  2002/07/15   0030      19:59    20:08    20:14
42   43    X2.8  1998/08/18   8307      08:14    08:24    08:32
43   44    X2.8  2001/12/11   9733      07:58    08:08    08:14
44   45    X2.8  2013/05/13   1748      15:48    16:05    16:16
45   46    X2.7  2015/05/05   2339      22:05    22:11    22:15
46   47    X2.7  1998/05/06   8210      07:58    08:09    08:20
47   48    X2.7  2003/11/03   0488      01:09    01:30    01:45
48   49    X2.6  2005/01/15   0720      22:25    23:02    23:31
49   50    X2.6  1997/11/27   8113      12:59    13:17    13:20

In [152]:
new_table.dtypes

rank          object
x_class       object
date          object
region        object
start_time    object
max_time      object
end_time      object
dtype: object

In [153]:
# Combine the date column with the time columns to convert to datetime format
df_st = pd.to_datetime(new_table['date'] + ' ' + new_table['start_time'])
df_mt = pd.to_datetime(new_table['date'] + ' ' + new_table['max_time'])
df_et = pd.to_datetime(new_table['date'] + ' ' + new_table['end_time'])

# Add the new columns of the datetimes
new_table['start_datetime'] = df_st
new_table['max_datetime'] = df_mt
new_table['end_datetime'] = df_et

# Drop the unneeded columns
new_table = new_table.drop('date', 1)
new_table = new_table.drop('start_time', 1)
new_table = new_table.drop('max_time', 1)
new_table = new_table.drop('end_time', 1)

In [154]:
# Change the order of the columns
new_table = new_table[['rank', 'x_class', 'start_datetime', 'max_datetime', 'end_datetime', 'region']]

# Replace all instances of '-' with '<NA>' as stated by the prompt
new_table = new_table.replace('-', '<NA>')

In [155]:
new_table

,rank,x_class,start_datetime,max_datetime,end_datetime,region
0,1,X28.0,2003-11-04 19:29:00,2003-11-04 19:53:00,2003-11-04 20:06:00,0486
1,2,X20.0,2001-04-02 21:32:00,2001-04-02 21:51:00,2001-04-02 22:03:00,9393
2,3,X17.2,2003-10-28 09:51:00,2003-10-28 11:10:00,2003-10-28 11:24:00,0486
3,4,X17.0,2005-09-07 17:17:00,2005-09-07 17:40:00,2005-09-07 18:03:00,0808
4,5,X14.4,2001-04-15 13:19:00,2001-04-15 13:50:00,2001-04-15 13:55:00,9415
5,6,X10.0,2003-10-29 20:37:00,2003-10-29 20:49:00,2003-10-29 21:01:00,0486
6,7,X9.4,1997-11-06 11:49:00,1997-11-06 11:55:00,1997-11-06 12:01:00,8100
7,8,X9.3,2017-09-06 11:53:00,2017-09-06 12:02:00,2017-09-06 12:10:00,2673
8,9,X9.0,2006-12-05 10:18:00,2006-12-05 10:35:00,2006-12-05 10:45:00,0930
9,10,X8.3,2003-11-02 17:03:00,2003-11-02 17:25:00,2003-11-02 17:39:00,0486
10,11,X8.2,2017-09-10 15:35:00,2017-09-10 16:06:00,2017-09-10 16:31:00,2673
11,12,X7.1,2005-01-20 06:36:00,2005-01-20 07:01:00,2005-01-20 07:26:00,0720
12,13,X6.9,2011-08-09 07:48:00,2011-08-09 08:05:00,2011-08-09 08:08:00,1263
13,14,X6.5,2006-12-06 18:29:00,2006-12-06 18:47:00,2006-12-06 19:00:00,0930
14,15,X6.2,2005-09-09 19:13:00,2005-09-09 20:04:00,2005-09-09 20:36:00,0808
15,16,X6.2,2001-12-13 14:20:00,2001-12-13 14:30:00,2001-12-13 14:35:00,9733
16,17,X5.7,2000-07-14 10:03:00,2000-07-14 10:24:00,2000-07-14 10:43:00,9077
17,18,X5.6,2001-04-06 19:10:00,2001-04-06 19:21:00,2001-04-06 19:31:00,9415
18,19,X5.4,2012-03-07 00:02:00,2012-03-07 00:24:00,2012-03-07 00:40:00,1429
19,20,X5.4,2003-10-23 08:19:00,2003-10-23 08:35:00,2003-10-23 08:49:00,0486
20,21,X5.4,2005-09-08 20:52:00,2005-09-08 21:06:00,2005-09-08 21:17:00,0808
21,22,X5.3,2001-08-25 16:23:00,2001-08-25 16:45:00,2001-08-25 17:04:00,9591
22,23,X4.9,1998-08-18 22:10:00,1998-08-18 22:19:00,1998-08-18 22:28:00,8307
23,24,X4.9,2014-02-25 00:39:00,2014-02-25 00:49:00,2014-02-25 01:03:00,1990
24,25,X4.8,2002-07-23 00:18:00,2002-07-23 00:35:00,2002-07-23 00:47:00,0039
25,26,X4.0,2000-11-26 16:34:00,2000-11-26 16:48:00,2000-11-26 16:56:00,9236
26,27,X3.9,1998-08-19 21:35:00,1998-08-19 21:45:00,1998-08-19 21:50:00,8307
27,28,X3.9,2003-11-03 09:43:00,2003-11-03 09:55:00,2003-11-03 10:19:00,0488
28,29,X3.8,2005-01-17 06:59:00,2005-01-17 09:52:00,2005-01-17 10:07:00,0720
29,30,X3.7,1998-11-22 06:30:00,1998-11-22 06:42:00,1998-11-22 06:49:00,8384
30,31,X3.6,2003-05-28 00:17:00,2003-05-28 00:27:00,2003-05-28 00:39:00,0365
31,32,X3.6,2004-07-16 13:49:00,2004-07-16 13:55:00,2004-07-16 14:01:00,0649
32,33,X3.6,2005-09-09 09:42:00,2005-09-09 09:59:00,2005-09-09 10:08:00,0808
33,34,X3.4,2006-12-13 02:14:00,2006-12-13 02:40:00,2006-12-13 02:57:00,0930
34,35,X3.4,2001-12-28 20:02:00,2001-12-28 20:45:00,2001-12-28 21:32:00,9767
35,36,X3.3,1998-11-28 04:54:00,1998-11-28 05:52:00,1998-11-28 06:13:00,8395
36,37,X3.3,2002-07-20 21:04:00,2002-07-20 21:30:00,2002-07-20 21:54:00,0039
37,38,X3.3,2013-11-05 22:07:00,2013-11-05 22:12:00,2013-11-05 22:15:00,1890
38,39,X3.2,2013-05-14 00:00:00,2013-05-14 01:11:00,2013-05-14 01:20:00,1748
39,40,X3.1,2014-10-24 21:07:00,2014-10-24 21:41:00,2014-10-24 22:13:00,2192
40,41,X3.1,2002-08-24 00:49:00,2002-08-24 01:12:00,2002-08-24 01:31:00,0069
41,42,X3.0,2002-07-15 19:59:00,2002-07-15 20:08:00,2002-07-15 20:14:00,0030
42,43,X2.8,1998-08-18 08:14:00,1998-08-18 08:24:00,1998-08-18 08:32:00,8307
43,44,X2.8,2001-12-11 07:58:00,2001-12-11 08:08:00,2001-12-11 08:14:00,9733
44,45,X2.8,2013-05-13 15:48:00,2013-05-13 16:05:00,2013-05-13 16:16:00,1748
45,46,X2.7,2015-05-05 22:05:00,2015-05-05 22:11:00,2015-05-05 22:15:00,2339
46,47,X2.7,1998-05-06 07:58:00,1998-05-06 08:09:00,1998-05-06 08:20:00,8210
47,48,X2.7,2003-11-03 01:09:00,2003-11-03 01:30:00,2003-11-03 01:45:00,0488
48,49,X2.6,2005-01-15 22:25:00,2005-01-15 23:02:00,2005-01-15 23:31:00,0720
49,50,X2.6,1997-11-27 12:59:00,1997-11-27 13:17:00,1997-11-27 13:20:00,8113

In [206]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
r = requests.get('http://cdaw.gsfc.nasa.gov/CME_list/radio/waves_type2.html')

In [207]:
root = BeautifulSoup(r.content,'html5lib')

In [208]:
table = root.find('pre')

In [209]:
row_marker = 0
content = table.get_text()
lines = content.split('\n')
for i in range(0,11):
    lines.pop(0);
lines.pop(len(lines)-1)
lines.pop(len(lines)-1)
lines.pop(len(lines)-1)
new_table = pd.DataFrame(columns=['start_date', 'start_time', 'end_date', 'end_time', 'start_frequency', 'end_frequency', 'flare_location', 'flare_region','flare_classification', 'cme_date', 'cme_time', 'cme_angle', 'cme_width', 'cme_speed'], index = range(0,len(lines)))
for line in lines:
    cols = line.split(' ')
    while '' in cols:
        cols.remove('')
    col_marker = 0
    while col_marker < 14:
        new_table.iat[row_marker, col_marker] = cols[col_marker]
        col_marker += 1
    row_marker += 1

In [210]:
new_table

,start_date,start_time,end_date,end_time,start_frequency,end_frequency,flare_location,flare_region,flare_classification,cme_date,cme_time,cme_angle,cme_width,cme_speed
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,74,79,312
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,Halo,360,878
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,Halo,360,464
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,263,165,296
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,133,155,712
5,1997/11/03,05:15,11/03,12:00,14000,250,S20W13,8100,C8.6,11/03,05:28,240,109,227
6,1997/11/03,10:30,11/03,11:30,14000,5000,S16W21,8100,M4.2,11/03,11:11,233,122,352
7,1997/11/04,06:00,11/05,04:30,14000,100,S14W33,8100,X2.1,11/04,06:10,Halo,360,785
8,1997/11/06,12:20,11/07,08:30,14000,100,S18W63,8100,X9.4,11/06,12:10,Halo,360,1556
9,1997/11/27,13:30,11/27,14:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,98,91,441
10,1997/12/12,22:45,12/12,23:20,14000,8000,N25W52,8116,B9.4,12/13,00:26,278,73,191
11,1998/01/25,15:03,01/25,15:18,14000,10000,N21E25,8141,C1.1,01/25,15:26,Halo,360,693
12,1998/03/29,03:40,03/29,03:52,14000,7000,SW90,-----,----,03/29,03:48,Halo,360,1397
13,1998/04/20,10:25,04/22,06:00,10000,35,S22W90,8194,M1.4,04/20,10:07,284,165,1863
14,1998/04/23,06:00,04/23,15:30,14000,200,S17E90,8210,X1.2,04/23,05:55,Halo,360,1691
15,1998/04/24,09:17,04/24,09:25,4700,2600,S10E90,8210,C8.9,04/24,08:55,100,84,1184
16,1998/04/27,09:20,04/27,10:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,Halo,360,1385
17,1998/04/29,16:30,04/29,17:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,Halo,360,1374
18,1998/05/02,14:25,05/02,14:50,5000,3000,S15W15,8210,X1.1,05/02,14:06,Halo,360,938
19,1998/05/06,08:25,05/06,08:35,14000,5000,S11W65,8210,X2.7,05/06,08:29,309,190,1099
20,1998/05/09,03:35,05/09,10:00,9000,400,S14W89,8210,M7.7,05/09,03:35,262,178,2331
21,1998/05/11,21:40,05/11,22:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,208,>301,830
22,1998/05/19,10:00,05/19,11:30,14000,3000,N29W46,8222,B7.9,05/19,10:27,268,139,801
23,1998/05/27,13:30,05/27,14:20,4000,1000,N19W62,8226,C7.5,05/27,13:45,175,268,878
24,1998/06/11,10:15,06/11,10:20,8000,4000,N16E86,8243,M1.4,06/11,10:28,123,177,1223
25,1998/06/16,18:20,06/17,21:00,12000,50,S22W90,8232,M1.0,06/16,18:27,341,281,1484
26,1998/06/20,19:39,06/20,20:00,2600,1800,Back,-----,----,06/20,18:20,Halo,360,964
27,1998/06/22,07:15,06/22,09:20,6000,2000,N16W46,8243,C2.9,06/22,05:01,265,59,206
28,1998/11/02,14:00,11/02,14:40,14000,4000,S25E47,8373,C4.4,11/02,14:18,116,169,661
29,1998/11/05,22:00,11/07,08:00,5000,50,N22W18,8375,M8.4,11/05,20:44,Halo,360,1118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,2014/04/04,14:02,04/04,14:07,14000,11000,N13E26,12027,C8.3,04/04,14:12,54,96,467
453,2014/04/18,13:05,04/18,22:50,14000,150,S20W34,12036,M7.3,04/18,13:25,Halo,360,1203
454,2014/05/07,16:24,05/07,23:18,16000,200,N11E53,12027,----,05/07,16:24,Halo,360,923
455,2014/05/08,03:21,05/08,05:26,16000,1100,S09W108,12051,----,05/08,03:24,Halo,360,847
456,2014/05/09,02:40,05/09,04:30,14000,500,S11W122,12051,----,05/09,02:48,Halo,360,1099
457,2014/05/10,04:32,05/10,08:37,16000,400,S11W136,12051,----,05/10,04:36,Halo,360,1086
458,2014/06/10,12:58,06/10,15:00,16000,1000,S17E82,12087,X1.5,06/10,13:30,Halo,360,1469
459,2014/06/12,22:14,06/12,22:35,14000,6000,S20W55,12085,M3.1,06/12,22:12,233,186,684
460,2014/07/30,07:44,07/30,08:00,6300,4500,N10E30,EP?,C1.5,07/30,07:00,13,254,700
461,2014/08/01,18:58,08/02,05:00,1000,150,S10E11,12127,M1.5,08/01,18:36,Halo,360h,789
462,2014/08/22,10:37,08/22,11:18,14000,6000,N12E01,12146,C2.2,08/22,11:12,Halo,360,600
463,2014/08/25,15:20,08/25,16:02,14000,4000,N05W36,12146,M2.0,08/25,15:36,Halo,360,555
464,2014/08/25,20:43,08/25,21:00,14000,7200,N07W43,12146,M3.9,08/25,20:48,273,177,711
465,2014/08/28,17:05,08/28,22:08,16000,600,S19E162,12157,----,08/28,17:24,Halo,360,766
466,2014/09/01,11:12,09/01,22:35,16000,600,N14E127,12158,----,09/01,11:12,Halo,360,1901
467,2014/09/09,00:05,09/09,13:00,11000,100,N12E29,12158,M4.5,09/09,00:06,Halo,360,920
468,2014/09/10,17:45,09/11,12:00,14000,100,N14E02,12158,X1.6,09/10,18:00,Halo,360,1267
469,2014/09/20,05:10,09/20,05:30,14000,9700,S11W89,12164,----,09/20,05:24,292,87,426
470,2014/09/22,06:13,09/22,06:50,16000,4900,N14W142,12158,----,09/22,06:12,342,252,618
471,2014/09/23,23:41,09/23,23:47,14000,12000,S13E33,12172,M2.3,09/23,23:36,109,134,331
472,2014/09/24,20:54,09/24,23:48,16000,500,N13E179,EP,----,09/24,21:30,Halo,360,1350
473,2014/10/02,21:34,10/02,21:56,3300,1900,S17W82,12173,M7.3,10/02,19:12,264,159,513
474,2014/10/10,18:11,10/10,18:33,2500,1500,S20W51,EP,C3.0,10/10,16:12,309,>210,782
475,2014/10/21,12:33,10/21,13:01,14000,8900,S18E36,12192,C4.4,10/21,12:48,152,142,260
476,2014/11/08,16:57,11/08,17:18,14000,7800,W90b,12203,----,11/08,16:36,305,141,426
477,2014/12/13,14:27,12/13,14:51,14000,3900,W90b,-----,----,12/13,14:24,Halo,360,2222
478,2014/12/17,04:09,12/17,04:19,2900,2100,S11E33,12241,M1.1,12/17,02:00,107,108,869
479,2014/12/17,05:00,12/17,05:09,14000,11500,S20E09,12242,M8.7,12/17,05:00,Halo,360,587
480,2014/12/18,22:31,12/18,22:54,5100,1300,S11E15,12241,M6.9,12/19,01:04,Halo,360,1195
481,2014/12/21,12:05,12/21,12:28,14000,7400,S14W25,12241,M1.0,12/21,12:12,Halo,360,669

In [211]:
#helper method

def isInt(s):
    try: 
        int(s)
        return True
    except ValueError:
        return False
    
#START OF STEP 4

# Replace all instances of '----' with 'NaN' as stated by the prompt
new_table = new_table.replace('----', 'NaN').replace('-----', 'NaN')

#Populate Halo_flare column
new_table['is_halo'] = new_table['cme_angle'].map(lambda x: x == 'Halo')

#Replace "Halo" with 'Na'
new_table = new_table.replace('Halo', 'NA')

#populate widthlowerbound column
new_table['width_lower_bound'] = new_table['cme_width'].map(lambda x: str(x)[0] == '>')

#remove any non-numeric part of the width column.
new_table['cme_width'] = new_table['cme_width'].map(lambda x: x if isInt(x) else "")

In [229]:
# Combine the date column with the time columns to convert to datetime format
new_table['start_datetime'] = pd.to_datetime(new_table['start_date'] + ' ' + new_table['start_time'])
new_table['end_datetime'] = pd.to_time(new_table['end_time'])

AttributeError: module 'pandas' has no attribute 'to_time'

In [204]:
# Drop the unneeded columns
new_table = new_table.drop('start_date', 1)
new_table = new_table.drop('start_time', 1)
new_table = new_table.drop('end_date', 1)
new_table = new_table.drop('end_time', 1)

new_table = new_table[['start_datetime', 'end_datetime', 'start_frequency', 
                       'end_frequency', 'flare_location', 'flare_region','flare_classification', 
                       'cme_date', 'cme_time', 'cme_angle', 'cme_width', 'cme_speed', 'is_halo', 
                       'width_lower_bound' ]]

new_table

,start_datetime,start_frequency,end_frequency,flare_location,flare_region,flare_classification,cme_date,cme_time,cme_angle,cme_width,cme_speed,is_halo,width_lower_bound
0,1997-04-01 14:00:00,8000,4000,S25E16,8026,M1.3,04/01,15:18,74,79,312,False,False
1,1997-04-07 14:30:00,11000,1000,S28E19,8027,C6.8,04/07,14:27,NA,360,878,True,False
2,1997-05-12 05:15:00,12000,80,N21W08,8038,C1.3,05/12,05:30,NA,360,464,True,False
3,1997-05-21 20:20:00,5000,500,N05W12,8040,M1.3,05/21,21:00,263,165,296,False,False
4,1997-09-23 21:53:00,6000,2000,S29E25,8088,C1.4,09/23,22:02,133,155,712,False,False
5,1997-11-03 05:15:00,14000,250,S20W13,8100,C8.6,11/03,05:28,240,109,227,False,False
6,1997-11-03 10:30:00,14000,5000,S16W21,8100,M4.2,11/03,11:11,233,122,352,False,False
7,1997-11-04 06:00:00,14000,100,S14W33,8100,X2.1,11/04,06:10,NA,360,785,True,False
8,1997-11-06 12:20:00,14000,100,S18W63,8100,X9.4,11/06,12:10,NA,360,1556,True,False
9,1997-11-27 13:30:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,98,91,441,False,False
10,1997-12-12 22:45:00,14000,8000,N25W52,8116,B9.4,12/13,00:26,278,73,191,False,False
11,1998-01-25 15:03:00,14000,10000,N21E25,8141,C1.1,01/25,15:26,NA,360,693,True,False
12,1998-03-29 03:40:00,14000,7000,SW90,NaN,NaN,03/29,03:48,NA,360,1397,True,False
13,1998-04-20 10:25:00,10000,35,S22W90,8194,M1.4,04/20,10:07,284,165,1863,False,False
14,1998-04-23 06:00:00,14000,200,S17E90,8210,X1.2,04/23,05:55,NA,360,1691,True,False
15,1998-04-24 09:17:00,4700,2600,S10E90,8210,C8.9,04/24,08:55,100,84,1184,False,False
16,1998-04-27 09:20:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,NA,360,1385,True,False
17,1998-04-29 16:30:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,NA,360,1374,True,False
18,1998-05-02 14:25:00,5000,3000,S15W15,8210,X1.1,05/02,14:06,NA,360,938,True,False
19,1998-05-06 08:25:00,14000,5000,S11W65,8210,X2.7,05/06,08:29,309,190,1099,False,False
20,1998-05-09 03:35:00,9000,400,S14W89,8210,M7.7,05/09,03:35,262,178,2331,False,False
21,1998-05-11 21:40:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,208,,830,False,True
22,1998-05-19 10:00:00,14000,3000,N29W46,8222,B7.9,05/19,10:27,268,139,801,False,False
23,1998-05-27 13:30:00,4000,1000,N19W62,8226,C7.5,05/27,13:45,175,268,878,False,False
24,1998-06-11 10:15:00,8000,4000,N16E86,8243,M1.4,06/11,10:28,123,177,1223,False,False
25,1998-06-16 18:20:00,12000,50,S22W90,8232,M1.0,06/16,18:27,341,281,1484,False,False
26,1998-06-20 19:39:00,2600,1800,Back,NaN,NaN,06/20,18:20,NA,360,964,True,False
27,1998-06-22 07:15:00,6000,2000,N16W46,8243,C2.9,06/22,05:01,265,59,206,False,False
28,1998-11-02 14:00:00,14000,4000,S25E47,8373,C4.4,11/02,14:18,116,169,661,False,False
29,1998-11-05 22:00:00,5000,50,N22W18,8375,M8.4,11/05,20:44,NA,360,1118,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,2014-04-04 14:02:00,14000,11000,N13E26,12027,C8.3,04/04,14:12,54,96,467,False,False
453,2014-04-18 13:05:00,14000,150,S20W34,12036,M7.3,04/18,13:25,NA,360,1203,True,False
454,2014-05-07 16:24:00,16000,200,N11E53,12027,NaN,05/07,16:24,NA,360,923,True,False
455,2014-05-08 03:21:00,16000,1100,S09W108,12051,NaN,05/08,03:24,NA,360,847,True,False
456,2014-05-09 02:40:00,14000,500,S11W122,12051,NaN,05/09,02:48,NA,360,1099,True,False
457,2014-05-10 04:32:00,16000,400,S11W136,12051,NaN,05/10,04:36,NA,360,1086,True,False
458,2014-06-10 12:58:00,16000,1000,S17E82,12087,X1.5,06/10,13:30,NA,360,1469,True,False
459,2014-06-12 22:14:00,14000,6000,S20W55,12085,M3.1,06/12,22:12,233,186,684,False,False
460,2014-07-30 07:44:00,6300,4500,N10E30,EP?,C1.5,07/30,07:00,13,254,700,False,False
461,2014-08-01 18:58:00,1000,150,S10E11,12127,M1.5,08/01,18:36,NA,,789,True,False
462,2014-08-22 10:37:00,14000,6000,N12E01,12146,C2.2,08/22,11:12,NA,360,600,True,False
463,2014-08-25 15:20:00,14000,4000,N05W36,12146,M2.0,08/25,15:36,NA,360,555,True,False
464,2014-08-25 20:43:00,14000,7200,N07W43,12146,M3.9,08/25,20:48,273,177,711,False,False
465,2014-08-28 17:05:00,16000,600,S19E162,12157,NaN,08/28,17:24,NA,360,766,True,False
466,2014-09-01 11:12:00,16000,600,N14E127,12158,NaN,09/01,11:12,NA,360,1901,True,False
467,2014-09-09 00:05:00,11000,100,N12E29,12158,M4.5,09/09,00:06,NA,360,920,True,False
468,2014-09-10 17:45:00,14000,100,N14E02,12158,X1.6,09/10,18:00,NA,360,1267,True,False
469,2014-09-20 05:10:00,14000,9700,S11W89,12164,NaN,09/20,05:24,292,87,426,False,False
470,2014-09-22 06:13:00,16000,4900,N14W142,12158,NaN,09/22,06:12,342,252,618,False,False
471,2014-09-23 23:41:00,14000,12000,S13E33,12172,M2.3,09/23,23:36,109,134,331,False,False
472,2014-09-24 20:54:00,16000,500,N13E179,EP,NaN,09/24,21:30,NA,360,1350,True,False
473,2014-10-02 21:34:00,3300,1900,S17W82,12173,M7.3,10/02,19:12,264,159,513,False,False
474,2014-10-10 18:11:00,2500,1500,S20W51,EP,C3.0,10/10,16:12,309,,782,False,True
475,2014-10-21 12:33:00,14000,8900,S18E36,12192,C4.4,10/21,12:48,152,142,260,False,False
476,2014-11-08 16:57:00,14000,7800,W90b,12203,NaN,11/08,16:36,305,141,426,False,False
477,2014-12-13 14:27:00,14000,3900,W90b,NaN,NaN,12/13,14:24,NA,360,2222,True,False
478,2014-12-17 04:09:00,2900,2100,S11E33,12241,M1.1,12/17,02:00,107,108,869,False,False
479,2014-12-17 05:00:00,14000,11500,S20E09,12242,M8.7,12/17,05:00,NA,360,587,True,False
480,2014-12-18 22:31:00,5100,1300,S11E15,12241,M6.9,12/19,01:04,NA,360,1195,True,False
481,2014-12-21 12:05:00,14000,7400,S14W25,12241,M1.0,12/21,12:12,NA,360,669,True,False